version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: sh_connect_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.1-apache
    container_name: sh_connect_wp
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ../src:/var/www/html/wp-content/plugins/shorthand_wordpress_connect
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      APACHE_RUN_USER: #1000
      APACHE_RUN_GROUP: #1000
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

volumes:
  db_data: {}
